<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class UniformsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table("itemrsos")->insert([
            // CITE
            // CORPO Shirt
            [
                'Department' => 'CITE',
                'Course' => 'BSIT',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CITE',
                'Course' => 'BSIT',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CITE',
                'Course' => 'BSIT',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CITE',
                'Course' => 'BSIT',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            //CORPO Pants
            [
                'Department' => 'CITE',
                'Course' => 'BSIT',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CITE',
                'Course' => 'BSIT',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CITE',
                'Course' => 'BSIT',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CITE',
                'Course' => 'BSIT',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            // RSO
            [
                'Department' => 'CITE',
                'Course' => 'BSIT',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CITE',
                'Course' => 'BSIT',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CITE',
                'Course' => 'BSIT',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CITE',
                'Course' => 'BSIT',
                'Gender' => 'Male',
                'Type' => 'Rso',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],

            // BSN //

            // CORPO Shirt
            [
                'Department' => 'CAHS',
                'Course' => 'BSN',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSN',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSN',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSN',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            //CORPO Pants
            [
                'Department' => 'CAHS',
                'Course' => 'BSN',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSN',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSN',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSN',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            // RSO
            [
                'Department' => 'CAHS',
                'Course' => 'BSN',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSN',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSN',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSN',
                'Gender' => 'Male',
                'Type' => 'Rso',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],

            // BSMLS
            // CORPO Shirt
            [
                'Department' => 'CAHS',
                'Course' => 'BSMLS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSMLS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSMLS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSMLS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            //CORPO Pants
            [
                'Department' => 'CAHS',
                'Course' => 'BSMLS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSMLS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSMLS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSMLS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            // RSO
            [
                'Department' => 'CAHS',
                'Course' => 'BSMLS',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSMLS',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSMLS',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSMLS',
                'Gender' => 'Male',
                'Type' => 'Rso',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],

            // BSPHARMA
            // CORPO Shirt
            [
                'Department' => 'CAHS',
                'Course' => 'BSPHARMA',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPHARMA',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPHARMA',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPHARMA',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            //CORPO Pants
            [
                'Department' => 'CAHS',
                'Course' => 'BSPHARMA',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPHARMA',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPHARMA',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPHARMA',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            // RSO
            [
                'Department' => 'CAHS',
                'Course' => 'BSPHARMA',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPHARMA',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPHARMA',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPHARMA',
                'Gender' => 'Male',
                'Type' => 'Rso',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],

            // BSPSYCH
            // CORPO Shirt
            [
                'Department' => 'CAHS',
                'Course' => 'BSPSYCH',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPSYCH',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPSYCH',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPSYCH',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            //CORPO Pants
            [
                'Department' => 'CAHS',
                'Course' => 'BSPSYCH',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPSYCH',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPSYCH',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPSYCH',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            // RSO
            [
                'Department' => 'CAHS',
                'Course' => 'BSPSYCH',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPSYCH',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPSYCH',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAHS',
                'Course' => 'BSPSYCH',
                'Gender' => 'Male',
                'Type' => 'Rso',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],

            //CEA
            //BSCE
            // CORPO Shirt
            [
                'Department' => 'CEA',
                'Course' => 'BSCE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            //CORPO Pants
            [
                'Department' => 'CEA',
                'Course' => 'BSCE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            // RSO
            [
                'Department' => 'CEA',
                'Course' => 'BSCE',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCE',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCE',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCE',
                'Gender' => 'Male',
                'Type' => 'Rso',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],

            // BSCPE
            // CORPO Shirt
            [
                'Department' => 'CEA',
                'Course' => 'BSCPE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCPE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCPE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCPE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            //CORPO Pants
            [
                'Department' => 'CEA',
                'Course' => 'BSCPE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCPE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCPE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCPE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            // RSO
            [
                'Department' => 'CEA',
                'Course' => 'BSCPE',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCPE',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCPE',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSCPE',
                'Gender' => 'Male',
                'Type' => 'Rso',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],

            //BSECE
            // CORPO Shirt
            [
                'Department' => 'CEA',
                'Course' => 'BSECE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSECE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSECE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSECE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            //CORPO Pants
            [
                'Department' => 'CEA',
                'Course' => 'BSECE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSECE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSECE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSECE',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            // RSO
            [
                'Department' => 'CEA',
                'Course' => 'BSECE',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSECE',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSECE',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSECE',
                'Gender' => 'Male',
                'Type' => 'Rso',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],

            //BSARCHI
            // CORPO Shirt
            [
                'Department' => 'CEA',
                'Course' => 'BSARCHI',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSARCHI',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSARCHI',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSARCHI',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            //CORPO Pants
            [
                'Department' => 'CEA',
                'Course' => 'BSARCHI',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSARCHI',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSARCHI',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSARCHI',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            // RSO
            [
                'Department' => 'CEA',
                'Course' => 'BSARCHI',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSARCHI',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSARCHI',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CEA',
                'Course' => 'BSARCHI',
                'Gender' => 'Male',
                'Type' => 'Rso',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],

            //CMA
            //BSA
            // CORPO Shirt
            [
                'Department' => 'CMA',
                'Course' => 'BSA',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSA',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSA',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSA',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            //CORPO Pants
            [
                'Department' => 'CMA',
                'Course' => 'BSA',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSA',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSA',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSA',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            // RSO
            [
                'Department' => 'CMA',
                'Course' => 'BSA',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSA',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSA',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSA',
                'Gender' => 'Male',
                'Type' => 'Rso',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],

            //BST

            // CORPO Shirt
            [
                'Department' => 'CMA',
                'Course' => 'BST',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BST',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BST',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BST',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            //CORPO Pants
            [
                'Department' => 'CMA',
                'Course' => 'BST',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BST',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BST',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BST',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            // RSO
            [
                'Department' => 'CMA',
                'Course' => 'BST',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BST',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BST',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BST',
                'Gender' => 'Male',
                'Type' => 'Rso',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],

            //CELA
            // CORPO Shirt
            [
                'Department' => 'CMA',
                'Course' => 'BSED',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSED',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSED',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSED',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            //CORPO Pants
            [
                'Department' => 'CMA',
                'Course' => 'BSED',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSED',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSED',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSED',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            // RSO
            [
                'Department' => 'CMA',
                'Course' => 'BSED',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSED',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSED',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CMA',
                'Course' => 'BSHM',
                'Gender' => 'Male',
                'Type' => 'Rso',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],

            //CELA
            //BSPOLSCI
            // CORPO Shirt
            [
                'Department' => 'CELA',
                'Course' => 'BSPOLSCI',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CELA',
                'Course' => 'BSPOLSCI',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CELA',
                'Course' => 'BSPOLSCI',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CELA',
                'Course' => 'BSPOLSCI',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            //CORPO Pants
            [
                'Department' => 'CELA',
                'Course' => 'BSPOLSCI',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CELA',
                'Course' => 'BSPOLSCI',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CELA',
                'Course' => 'BSPOLSCI',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CELA',
                'Course' => 'BSPOLSCI',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            // RSO
            [
                'Department' => 'CELA',
                'Course' => 'BSPOLSCI',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CELA',
                'Course' => 'BSPOLSCI',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CELA',
                'Course' => 'BSPOLSCI',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CELA',
                'Course' => 'BSPOLSCI',
                'Gender' => 'Male',
                'Type' => 'Rso',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],

            //CCJE
            //BSCRIM
            // CORPO Shirt
            [
                'Department' => 'CCJE',
                'Course' => 'BSCRIM',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CCJE',
                'Course' => 'BSCRIM',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CCJE',
                'Course' => 'BSCRIM',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CCJE',
                'Course' => 'BSCRIM',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            //CORPO Pants
            [
                'Department' => 'CCJE',
                'Course' => 'BSCRIM',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CCJE',
                'Course' => 'BSCRIM',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CCJE',
                'Course' => 'BSCRIM',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CCJE',
                'Course' => 'BSCRIM',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            // RSO
            [
                'Department' => 'CCJE',
                'Course' => 'BSCRIM',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CCJE',
                'Course' => 'BSCRIM',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CCJE',
                'Course' => 'BSCRIM',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CCJE',
                'Course' => 'BSCRIM',
                'Gender' => 'Male',
                'Type' => 'Rso',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],

            // CAS
            // CORPO Shirt
            [
                'Department' => 'CAS',
                'Course' => 'CAS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAS',
                'Course' => 'CAS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAS',
                'Course' => 'CAS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAS',
                'Course' => 'CAS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            //CORPO Pants
            [
                'Department' => 'CAS',
                'Course' => 'CAS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAS',
                'Course' => 'CAS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAS',
                'Course' => 'CAS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAS',
                'Course' => 'CAS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            // RSO
            [
                'Department' => 'CAS',
                'Course' => 'CAS',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAS',
                'Course' => 'CAS',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAS',
                'Course' => 'CAS',
                'Gender' => 'Male',
                'Type' => 'RSO',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'CAS',
                'Course' => 'CAS',
                'Gender' => 'Male',
                'Type' => 'Rso',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            

            //SHS
            // CORPO Shirt
            [
                'Department' => 'SHS',
                'Course' => 'SHS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'SHS',
                'Course' => 'SHS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'SHS',
                'Course' => 'SHS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'SHS',
                'Course' => 'SHS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Shirt',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            //CORPO Pants
            [
                'Department' => 'SHS',
                'Course' => 'SHS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'S',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'SHS',
                'Course' => 'SHS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'M',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'SHS',
                'Course' => 'SHS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'L',
                'Stock' => '10',
                'Reserved' => '0',
            ],
            [
                'Department' => 'SHS',
                'Course' => 'SHS',
                'Gender' => 'Male',
                'Type' => 'Corporate',
                'Body' => 'Pants',
                'Size' => 'XL',
                'Stock' => '10',
                'Reserved' => '0',
            ],



        ]);
    }
}
